<?php 
	$this->layout("layout", [
		"location" => "pages",
	])
?>

<div class="page-header">
	<h1><?= $this->e($title) ?></h1>
</div>

<div class="row">
	<div class="col-sm-8">
		<?= $this->md($page, true) ?>
	</div>
	<div class="col-sm-4">
		<ul class="nav nav-stacked nav-pills" style="border-radius: 4px; border: 1px solid #ccc">
			<li class="bg-primary">
				<a class="bg-primary" style="background-color: inherit; color: inherit">
					<span class="glyphicon glyphicon-list"></span>
					Table Of Contents
				</a>
			</li>
			<?php foreach ($pages as $page) : ?>
			<li>
				<a href="<?= $baseUrl->mod("./pages/". rawurlencode($page)) ?>">
				<?= $this->e($page) ?>
				</a>
			</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>

