<?php $this->layout("layout") ?>

<div class="page-header">
	<h1>
		Github Repositories
		<small>Manage your pharext webhook</small>
	</h1>
</div>

<table class="table table-hover">
	<thead>
		<tr>
			<th colspan="2">Repo</th>
			<th class="text-right">Last Pushed</th>
			<th class="text-center">Hook</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($repos as $repo) : ?>
		<tr class="<?= $this->check($repo) ? "success" : "" ?>">
			<td>
				<?php if ($repo->fork) : ?>
					<span title="fork" class="octicon octicon-repo-forked" aria-hidden="true"></span>
				<?php elseif ($repo->private) : ?>
					<span title="fork" class="octicon octicon-key" aria-hidden="true"></span>
				<?php else : ?>
					<span title="repo" class="octicon octicon-repo" aria-hidden="true"></span>
				<?php endif; ?>
			</td>
			<th>
				<a href="<?= $baseUrl->mod(":./github/repo/".$repo->full_name) ?>">
					<big class="text-primary" title="<?= $this->e($repo->description) ?>"><?= $this->e($repo->name) ?></big>
				</a>
				<br>
				<small><?= $this->e($this->shorten($repo->description)) ?></small>
			</th>
			<td class="text-right"><time datetime="<?= $this->e($repo->pushed_at) ?>"><?= $this->e($this->utc($repo->pushed_at)->format("Y-m-d H:i T")) ?></time></td>
			<td class="text-center">
				<?php if ($this->check($repo)) : ?>
				<form class="form" style="display: inline-block" method="post" action="<?= $baseUrl->mod(":./github/repo/". $repo->full_name ."/hook/del") ?>">
					<input type="hidden" name="returnback" value="1">
					<button type="submit" class="btn btn-block btn-danger">
						<span class="glyphicon glyphicon-remove"></span>
						Remove Hook
					</button>
				</form>
				<?php else : ?>
				<form class="form-inline" style="display: inline-block" method="post" action="<?= $baseUrl->mod(":./github/repo/". $repo->full_name ."/hook/add") ?>">
						<div class="checkbox">
							<label for="hook-tag">
								<input id="hook-tag" type="checkbox" name="tag" value="1" checked>
								Release
							</label>
						</div>
						<div class="checkbox">
							<label for="hook-release">
								<input id="hook-release" type="checkbox" name="release" value="1" checked>
								Upload
							</label>
						</div>
					<input type="hidden" name="returnback" value="1">
					<button type="submit" class="btn btn-block btn-primary">
						<span class="glyphicon glyphicon-plus"></span>
						Enable Hook
					</button>
				</form>
				<?php endif; ?>
			</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<nav>
	<ul class="pager">
		<li class="<?= $links->getFirst() ?"":"disabled" ?>"><a href="?page=<?= $links->getPage("first") ?>" title="First Page"><span class="glyphicon glyphicon-fast-backward"></span></a></li>
		<li class="<?= $links->getPrev() ?"":"disabled" ?>"><a href="?page=<?= $links->getPage("prev") ?>" rel="prev" title="Previous Page"><span class="glyphicon glyphicon-chevron-left"></span> Previous</a></li>
		<li class="<?= $links->getNext() ?"":"disabled" ?>"><a href="?page=<?= $links->getPage("next") ?>" rel="next" title="Next Page">Next <span class="glyphicon glyphicon-chevron-right"></span></a></li>
		<li class="<?= $links->getLast() ?"":"disabled" ?>"><a href="?page=<?= $links->getPage("last") ?>" title="Last Page"><span class="glyphicon glyphicon-fast-forward"></span></a></li>
	</ul>
</nav>
