<?php $this->layout("layout") ?>

<div class="page-header">
	<h1>
		<?php if (isset($repo)) : ?>
			<?php if ($repo->fork) : ?>
				<span title="fork" class="mega-octicon octicon-repo-forked" aria-hidden="true"></span>
			<?php elseif ($repo->private) : ?>
				<span title="fork" class="mega-octicon octicon-key" aria-hidden="true"></span>
			<?php else : ?>
				<span title="repo" class="mega-octicon octicon-repo" aria-hidden="true"></span>
			<?php endif; ?>
			<?= $this->e($repo->name) ?>
		<?php elseif (isset($name)) : ?>
			<?= $this->e($name) ?>
		<?php else : ?>
			Unknown Repository
		<?php endif; ?>
			- <small>Github</small>
	</h1>
</div>

<?php if (isset($exception)) : ?>
	<?= $this->fetch("alert") ?>
<?php elseif (isset($repo)) : ?>

<div class="row">
	<div class="col-md-6">
		<div class="well">
			<p><?= $this->e($repo->description) ?></p>
		</div>
	</div>
	<div class="col-md-6">
		<div class="row text-center">
			<div class="col-md-4">
				<span title="Number of watchers" class="mega-octicon octicon-eye" aria-hidden="true"></span>
				<br>
				<span class="label label-success">
					<?= $repo->watchers_count ?> Watchers
				</span>
			</div>
			<div class="col-md-4">
				<span title="Number of stars" class="mega-octicon octicon-star" aria-hidden="true"></span>
				<br>
				<span class="label label-primary">
					<?= $repo->stargazers_count ?> Stars
				</span>
			</div>
			<div class="col-md-4">
				<span title="Number of forks" class="mega-octicon octicon-repo-forked" aria-hidden="true"></span>
				<br>
				<span class="label label-default">
					<?= $repo->forks_count ?> Forks
				</span>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="row">
			<div class="col-md-8">
				<p>Has a <code>config*.m4</code> file?</p>
			</div>
			<div class="col-md-4 text-center">
				<p>
					<?php if (!empty($repo->config_m4)) : ?>
					<span class="label label-info">YES</span>
					<?php else : ?>
					<span class="label label-warning">NO</span>
					<?php endif; ?>
				</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
				<p>Has a <code>package*.xml</code> file?</p>
			</div>
			<div class="col-md-4 text-center">
				<p>
					<?php if (!empty($repo->package_xml)) : ?>
					<span class="label label-info">YES</span>
					<?php else : ?>
					<span class="label label-warning">NO</span>
					<?php endif; ?>
				</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
				<p>Has a <code>pharext_package.php</code> file?</p>
			</div>
			<div class="col-md-4 text-center">
				<p>
					<?php if (!empty($repo->pharext_package_php)) : ?>
					<span class="label label-info">YES</span>
					<?php else : ?>
					<span class="label label-warning">NO</span>
					<?php endif; ?>
				</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
				<p>Is the <code>pharext</code> hook enabled?</p>
			</div>
			<div class="col-md-4 text-center">
					<?php if ($this->check($repo)) : ?>
					<span class="label label-info">YES</span>
					<?php else : ?>
					<span class="label label-warning">NO</span>
					<?php endif; ?>
			</div>
		</div>
	</div>

	<div class="col-md-6">
		
		<div class="row text-center">
			<div class="col-md-6">
				<form method="post" action="<?= $baseUrl->mod("./github/repo/". $repo->full_name ."/hook/add") ?>"> 
				<button type="submit" class="btn btn-lg btn-block btn-success <?= $this->check($repo) ? "disabled":"" ?>">Enable Hook</button>
				</form>
			</div>
			<div class="col-md-6">
				<form method="post" action="<?= $baseUrl->mod("./github/repo/". $repo->full_name ."/hook/del") ?>"> 
				<button class="btn btn-lg btn-block btn-danger <?= $this->check($repo) ? "":"disabled" ?>">Disable Hook</button>
				</form>
			</div>
		</div>
		</form>
	</div>
</div>

<h2>Release History</h2>
<?php if (empty($repo->tags) || !count((array) $repo->tags)) : ?>
<div class="alert alert-warning" role="alert">
	<p class="text-danger">No releases or tags found.</p>
</div>
<?php endif; ?>

<?php foreach ($repo->tags as $name => $v) : ?>
<div class="panel panel-<?= empty($v->release) ? "info": "primary" ?>">
	<div class="panel-heading">
		<h3 class="panel-title">
			<?php if (empty($v->release)) : ?>
				<?= $this->e($v->tag->name) ?>
				<span class="label label-default pull-right">Tag</span>
			<?php else : ?>
				<?= $this->e($v->release->name) ?>
				<span class="label label-info pull-right">Release</span>
			<?php endif; ?>
		</h3>
	</div>
	<div class="panel-body">
		<?php if (!empty($v->release)) : ?>
			<p><?= $this->md($v->release->body) ?></p>
		<?php endif; ?>
		<ul class="list-inline">
			<li>
				<span class="octicon octicon-tag" title="Tag"></span>
				<span class="label label-default"><?= $this->e($v->tag->name) ?></span>
			</li>

			<?php if (!empty($v->release)) : ?>
			<li>
				<span class="octicon octicon-git-branch" title="Branch"></span>
				<span class="label label-default"><?= $this->e($v->release->target_commitish) ?></span>
			</li>
			<li>
				<span class="octicon octicon-clock" title="Date"></span>
				<span class="label label-default">
					<time datetime="<?= $v->release->published_at ?>">
						<?= $this->utc($v->release->published_at)->format("Y-m-d H:i T") ?>
					</time>
				</span>
			<?php endif; ?>
		</ul>
	</div>
</div>
<?php endforeach; ?>

<?php endif; ?>
