<?php $this->layout("layout", ["title" => "Github: ". (isset($repo) ? $repo->name : $name)]) ?>

<div class="page-header">
	<h1>
		<?php if (isset($repo)) : ?>
			<?php if ($repo->fork) : ?>
				<span title="fork" class="mega-octicon octicon-repo-forked" aria-hidden="true"></span>
			<?php elseif ($repo->private) : ?>
				<span title="fork" class="mega-octicon octicon-key" aria-hidden="true"></span>
			<?php else : ?>
				<span title="repo" class="mega-octicon octicon-repo" aria-hidden="true"></span>
			<?php endif; ?>
			<?= $this->e($repo->name) ?>
		<?php elseif (isset($name)) : ?>
			<?= $this->e($name) ?>
		<?php else : ?>
			Unknown Repository
		<?php endif; ?>
			- <small>Github</small>
	</h1>
</div>

<div class="row">
	<div class="col-sm-8">
		<div class="well">
			<p><?= $this->e($repo->description) ?></p>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="row text-center">
			<div class="col-sm-4">
				<span title="Number of watchers" class="octicon octicon-eye" aria-hidden="true"></span>
				<br>
				<span class="label label-success">
					<?= $repo->watchers_count ?> Watchers
				</span>
			</div>
			<div class="col-sm-4">
				<span title="Number of stars" class="octicon octicon-star" aria-hidden="true"></span>
				<br>
				<span class="label label-primary">
					<?= $repo->stargazers_count ?> Stars
				</span>
			</div>
			<div class="col-sm-4">
				<span title="Number of forks" class="octicon octicon-repo-forked" aria-hidden="true"></span>
				<br>
				<span class="label label-default">
					<?= $repo->forks_count ?> Forks
				</span>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-6">
		<div class="row">
			<div class="col-sm-8">
				<p>Has a <code>config*.m4</code> file?</p>
			</div>
			<div class="col-sm-4">
				<p>
					<?php if (!empty($repo->config_m4)) : ?>
					<span class="label label-info">YES</span>
					<?php else : ?>
					<span class="label label-warning">NO</span>
					<?php endif; ?>
				</p>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-8">
				<p>Has a <code>package*.xml</code> file?</p>
			</div>
			<div class="col-sm-4">
				<p>
					<?php if (!empty($repo->package_xml)) : ?>
					<span class="label label-info">YES</span>
					<?php else : ?>
					<span class="label label-warning">NO</span>
					<?php endif; ?>
				</p>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-8">
				<p>Has a <code>pharext_package.php</code> file?</p>
			</div>
			<div class="col-sm-4">
				<p>
					<?php if (!empty($repo->pharext_package_php)) : ?>
					<span class="label label-info">YES</span>
					<?php else : ?>
					<span class="label label-warning">NO</span>
					<?php endif; ?>
				</p>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-8">
				<p>Is the <code>pharext</code> hook enabled?</p>
			</div>
			<div class="col-sm-4">
					<?php if (!empty($hook)) : ?>
					<span class="label label-info">YES</span>
					<?php else : ?>
					<span class="label label-warning">NO</span>
					<?php endif; ?>
			</div>
		</div>
	</div>

	<div class="col-sm-6">
		<div class="row">
			<form method="post" action="<?= $baseUrl->mod(":./github/repo/". $repo->full_name ."/hook/" . (!empty($hook) ? "upd" : "add")) ?>">
				<div class="col-sm-6">
					<h4>PHARext Options:</h4>
					<div class="checkbox">
						<label for="hook-zend">
							<input id="hook-zend" type="checkbox" name="zend" value="1" <?= (!empty($hook) && !empty($hook->config->zend)) ? "checked":""?>>
							Mark as a ZendExtension.
						</label>
					</div>
					<div class="checkbox <?= empty($repo->package_xml) ? "disabled text-muted":"" ?>">
						<label for="hook-pecl">
							<input id="hook-pecl" type="checkbox" name="pecl" value="1" <?= (!empty($hook) && !empty($hook->config->pecl)) ? "checked":""?> <?= empty($repo->package_xml) ? "disabled":"" ?>>
							Use PECL package XML file.
						</label>
					</div>
				</div>
				<div class="col-sm-6">
					<h4>Hook Options:</h4>
						<div class="checkbox">
							<label for="hook-tag">
								<input id="hook-tag" type="checkbox" name="tag" value="1" <?= (empty($hook) || in_array("create", $hook->events)) ? "checked":"" ?>>
								Automatically create a release when I push a tag.
							</label>
						</div>
						<div class="checkbox">
							<label for="hook-release">
								<input id="hook-release" type="checkbox" name="release" value="1" <?= (empty($hook) || in_array("release", $hook->events)) ? "checked":"" ?>>
								Automatically upload a PHARext package as an asset to a release.
							</label>
						</div>
				</div>
				<?php if ($this->check($repo)) : ?>
				<div class="col-sm-6">
					<button type="submit" class="btn btn-lg btn-block btn-info">
						<span class="glyphicon glyphicon-ok-circle"></span>
						Update Hook
					</button>
				</div>
				<?php else : ?>
				<div class="col-sm-6 col-sm-offset-6">
					<button type="submit" class="btn btn-lg btn-block btn-success">
						<span class="octicon octicon-plug"></span>
						Enable Hook
					</button>
				</div>
				<?php endif; ?>
			</form>
			<!-- column wrapping! -->
			<?php if ($this->check($repo)) : ?>
			<div class="col-sm-6">
				<form method="post" action="<?= $baseUrl->mod(":./github/repo/". $repo->full_name ."/hook/del") ?>">
				<button class="btn btn-lg btn-block btn-danger">
					<span class="glyphicon glyphicon-remove-circle"></span>
					Remove Hook
				</button>
				</form>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>

<h2>Release History</h2>
<?php if (empty($repo->tags) || !count((array) $repo->tags)) : ?>
<div class="alert alert-warning" role="alert">
	<p class="text-danger">No releases or tags found.</p>
</div>
<?php endif; ?>

<?php foreach ($repo->tags as $name => $v) : ?>
<div class="panel panel-<?= empty($v->release) ? "info": "primary" ?>">
	<div class="panel-heading">
		<h3 class="panel-title">
			<?php if (empty($v->release)) : ?>
				<?= $this->e($v->tag->name) ?>
				<span class="label label-default pull-right">Tag</span>
			<?php else : ?>
				<?= $this->e($v->release->name ?: $v->tag->name) ?>
				<span class="label label-info pull-right">Release</span>
			<?php endif; ?>
		</h3>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-sm-8">
		<?php if (!empty($v->release)) : ?>
			<p><?= $this->md($v->release->body) ?></p>
		<?php endif; ?>
				<ul class="list-inline">
					<li>
						<span class="octicon octicon-tag" title="Tag"></span>
						<span class="label label-default"><?= $this->e($v->tag->name) ?></span>
					</li>

					<?php if (!empty($v->release)) : ?>
					<li>
						<span class="octicon octicon-git-branch" title="Branch"></span>
						<span class="label label-default"><?= $this->e($v->release->target_commitish) ?></span>
					</li>
					<li>
						<span class="octicon octicon-clock" title="Date"></span>
						<span class="label label-default">
							<time datetime="<?= $v->release->published_at ?>">
								<?= $this->utc($v->release->published_at)->format("Y-m-d H:i T") ?>
							</time>
						</span>
					<?php endif; ?>
				</ul>
			</div>
			<div class="col-sm-4">
			<?php if (!empty($v->release->assets)) : ?>
				<ul class="list-inline pull-right">
					<?php foreach ($v->release->assets as $asset) : ?>
					<?php if (fnmatch("*.ext.phar", $asset->name)) : ?>
					<li>
						<a class="btn btn-success" href="<?= $this->e($asset->browser_download_url) ?>">
							<span class="octicon octicon-package"></span>
							<?= $this->e($asset->name) ?>
						</a>
					</li>
					<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			<?php else: ?>
				<form class="form-inline pull-right" method="post" action="<?= $baseUrl->mod(":./github/repo/". $repo->full_name ."/release") ?>">
					<input type="hidden" name="tag" value="<?= $this->e($v->tag->name) ?>">
					<div class="checkbox">
						<label for="hook-zend">
							<input id="hook-zend" type="checkbox" name="zend" value="1" <?= (!empty($hook) && !empty($hook->config->zend)) ? "checked":""?>>
							Mark as a ZendExtension.
						</label>
					</div>
					<div class="checkbox <?= empty($repo->package_xml) ? "disabled text-muted":"" ?>">
						<label for="hook-pecl">
							<input id="hook-pecl" type="checkbox" name="pecl" value="1" <?= (!empty($hook) && !empty($hook->config->pecl)) ? "checked":""?> <?= empty($repo->package_xml) ? "disabled":"" ?>>
							Use PECL package XML file.
						</label>
					</div>
					<button class="btn btn-warning">
						<span class="octicon octicon-package"></span>
						Release PHARext package
					</button>
				</form>
			<?php endif; ?>
			
			</div>
		</div>
	</div>
</div>
<?php endforeach; ?>

