
<nav class="navbar navbar-default">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?=$baseUrl->mod("./")?>">PHARext</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<?php if ($location == "pages") : ?>
				<li class="active dropdown">
					<a
						class="dropdown-toggle"
						data-toggle="dropdown"
						role="button"
						aria-expand="false"
						href="<?=$baseUrl->mod("./pages/Home")?>">
						About
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu" role="menu">
						<?php foreach ($pages as $page) : ?>
						<li><a href="<?= $baseUrl->mod("./pages/". rawurlencode($page)) ?>">
							<?= $this->e($page) ?></a></li>
						<?php endforeach; ?>
					</ul>
				</li>
				<?php else : ?>
				<li><a href="<?=$baseUrl->mod("./pages/Home")?>">About</a></li>
				<?php endif; ?>
				<li
					<?php if ($location == "github") : ?>
					class="active"
					<?php endif; ?>
					><a href="<?=$baseUrl->mod("./github")?>">Github</a>
				</li>
			</ul>
			<?php if (isset($session)) : ?>
				<?php if (isset($session->github)) : ?>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
							<img src="<?= $session->github->owner["avatar_url"] ?>" 
							 class="img-circle"
							 alt="avatar"
							 width="32"
							 style="margin:-15px 0px">
							<abbr title="<?= $this->e($session->github->owner["name"]) ?>">
								<?= $this->e($session->github->owner["login"]) ?>
							</abbr>
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="<?= $baseUrl->mod("./reset") ?>">
									Signout
								</a>
							</li>
						</ul>
					</li>
				</ul>
				<?php endif; ?>
			<?php endif; ?>

			<?php /*
			<ul>
				<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
				<li><a href="#">Link</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li class="divider"></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#">Link</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
					</ul>
				</li>
			</ul>
			 */ ?>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>
